# Generated by Django 3.2.5 on 2021-12-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.DecimalField(decimal_places=2, max_digits=20)),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OneDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prices', models.DecimalField(decimal_places=2, max_digits=20)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OneHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prices', models.DecimalField(decimal_places=2, max_digits=20)),
                ('time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
