# Generated by Django 3.2.5 on 2021-12-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historic',
            options={'ordering': ['-day']},
        ),
        migrations.AlterModelOptions(
            name='oneday',
            options={'ordering': ['-time']},
        ),
    ]
