# Generated by Django 3.2.5 on 2021-12-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_auto_20211211_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historic',
            old_name='prices',
            new_name='Prices',
        ),
    ]
