# Generated by Django 3.2.5 on 2021-12-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0003_rename_prices_historic_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historic',
            options={'ordering': ['-time']},
        ),
        migrations.RenameField(
            model_name='historic',
            old_name='day',
            new_name='time',
        ),
    ]
