# Generated by Django 3.2.5 on 2021-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0004_auto_20211211_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
