# Generated by Django 3.2.5 on 2021-12-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0005_spotprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotprice',
            old_name='prices',
            new_name='Prices',
        ),
    ]
