# Generated by Django 3.2.5 on 2021-12-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0006_rename_prices_spotprice_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prices', models.DecimalField(decimal_places=2, max_digits=20)),
                ('time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='OneWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prices', models.DecimalField(decimal_places=2, max_digits=20)),
                ('time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.RenameModel(
            old_name='Historic',
            new_name='OneYear',
        ),
    ]
