# Generated by Django 3.2.5 on 2021-12-18 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0007_auto_20211212_0111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OneHour',
            new_name='Minute',
        ),
        migrations.RenameModel(
            old_name='OneWeek',
            new_name='Month',
        ),
        migrations.RenameModel(
            old_name='OneDay',
            new_name='Year',
        ),
        migrations.DeleteModel(
            name='OneMonth',
        ),
        migrations.DeleteModel(
            name='OneYear',
        ),
        migrations.DeleteModel(
            name='SpotPrice',
        ),
    ]
