# Generated by Django 3.2.5 on 2021-12-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0008_auto_20211218_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prices', models.DecimalField(decimal_places=2, max_digits=20)),
                ('time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prices', models.DecimalField(decimal_places=2, max_digits=20)),
                ('time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.RenameModel(
            old_name='Minute',
            new_name='Day',
        ),
    ]
